# Generated by Django 5.0.7 on 2024-08-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_chess_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Нумерация фотографий')),
                ('photo', models.ImageField(upload_to='images', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фото',
                'ordering': ['-time_create'],
            },
        ),
    ]
