# Generated by Django 5.0.7 on 2024-08-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_chess_app', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
    ]
