# Generated by Django 5.0.7 on 2024-08-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_chess_app', '0003_video_is_published_alter_photo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('logo_url', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка на партнёра')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Логотопы',
                'verbose_name_plural': 'Лого',
                'ordering': ['-time_create'],
            },
        ),
    ]
